# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
    - echo $DOCKER_PASSWORD | docker login docker.io -u $DOCKER_USERNAME --password-stdin
    - echo $CR_PAT | docker login ghcr.io -u $CR_USER --password-stdin

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Version }}
      - -s -w -X main.ferretVersion={{ .Env.FERRET_VERSION }}

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    # Can be used to change the archive formats for specific GOOSs.
    # Most common use case is to archive as zip on Windows.
    # Default is empty.
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - lab
    skip_push: false
    dockerfile: Dockerfile.release
    image_templates:
      - "docker.io/montferret/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
      - "docker.io/montferret/{{ .ProjectName }}:latest"
      - "ghcr.io/montferret/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/montferret/{{ .ProjectName }}:latest"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'